// <auto-generated />
namespace PomodoroGamify.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FixQuests80 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixQuests80));
        
        string IMigrationMetadata.Id
        {
            get { return "201901241711226_FixQuests8.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
